# Generated by Django 4.2.3 on 2023-12-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filomenas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='formulario_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
